#!/bin/sh
set -e

user=testing

if [ $(id -u) = 0 ]
then
    adduser --quiet --system --group --no-create-home $user
    chown -R $user .
    runuser="runuser -p -u $user --"
else
    runuser=""
fi

$runuser python3 -m pytest -k 'not test_find_in_path'

if [ $(id -u) = 0 ]
then
    deluser --quiet $user
fi
